name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Apifox CLI
      run: npm install -g apifox-cli

    - name: Running Test Scenario
      run: apifox run https://api.apifox.com/api/v1/projects/4456908/api-test/ci-config/430625/detail?token=xAIIa_xpAXU7qn7j55HDQd -r html,cli --database-connection ./database-connections.json
